

SELECT *
FROM INFORMATION_SCHEMA .ROUTINES Rou
     CROSS APPLY
     (
       SELECT OBJECT_DEFINITION (OBJECT_ID (Rou.ROUTINE_NAME)) AS ROUTINE_DEFINITION
     ) AS Def
WHERE Def .ROUTINE_DEFINITION LIKE '%%'